### PR TITLE
Fixes to help approval on extensions.gnome.org

### PR DESCRIPTION
**Pull request by AndrewZaech**
-Remove Lang in favor of GObject
-Use Gettext for string translations
-Remove deprecated 'actor' call

### CODE REVIEW

**Comment by AndrewZaech** [comment]
I saw your post on reddit, thought I'd help you out

You should also change your version number in metadata.json to a numerical value, and change the shell versions to "3.36", "3.38", "40". 

Hope this helps get you approval!

**Comment by tofutech** [comment]
Thanks! I admittedly haven't had a chance to clean up the code, this helps a lot!

**Comment by AndrewZaech** [comment]
Happy to help! 

I just noticed some line indentations are a bit off with this PR. Not sure what went wrong there, sorry about that

**Comment by ShrirajHegde** [comment]
@AndrewZaech 
@tofutech  is it possible to maintain/at least gnome 40fy this https://github.com/julio641742/fedora-update

It is a really useful extension and is no longer maintained. 

The author isn't accepting pull requests either.

**Comment by ShrirajHegde** [comment]
I am talking about [Fedora Update Indicator](https://github.com/julio641742/fedora-update)

**Pull request merged**
