### PR TITLE
Add extension settings with icon and icon size options

### PR DESCRIPTION
**Pull request by AndrewZaech**
Add Extension Settings:

Screen Grab 20210514T144559

Tested on GNOME 40 and GNOME 3.36.4

You might need to add some sort of credits/disclaimers about the icons as they may be copyrighted

### CODE REVIEW

**Comment by tofutech** [comment]
I'm thinking of changing the name of the extension now that there is more than just a Fedora option, if you have suggestions that would be wonderful!

**Comment by AndrewZaech** [comment]
Hmm, off the top of my head - Tofutech Menu or QuickLinks Menu.  

Probably not the best, but I couldn't think of anything else haha

**Comment by tofutech** [comment]
Tofu Menu actually works really well!

**Comment by AndrewZaech** [comment]
Sounds good to me. If you need help with anything drop a reply in this thread and I'll see if I can help

**Pull request merged**
